apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: main-rest-api-backend
  name: main-rest-api-backend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: main-rest-api-backend
    spec:
      containers:
      - image: main_rest_api_backend
        name: main-rest-api-backend
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
