apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-service
  name: mongo-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongo-service
    spec:
      containers:
      - image: mongo:latest
        name: mongo-service
        ports:
        - containerPort: 27018
        resources: {}
      restartPolicy: Always
status: {}
