apiVersion: v1
kind: Service
metadata:
  name: mainbackendservice
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 4000
  selector:
    app: mainbackend
  externalIPs:
  - 192.168.99.101