apiVersion: v1
kind: Service
metadata:
  name: mainbackservise
spec:
  type: LoadBalancer
  selector:
    app: mainbacklabel
  ports:
    - port: 8080
      targetPort: 3000
  externalIPs:
  - 192.168.99.100
